version: '3.8'

services:
  combined_service:
    build: .
    image: combined-mysql-backend
    container_name: combined_service_container
    ports:
      - "3307:3306"
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: valentin
      MYSQL_DATABASE: almfit
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/almfit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: valentin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always
